# Getting Started with Pandas
pandas contains data structures and data manipulation tools designed to make data cleaning and analysis fast and easy on Python.
<br> pandas adopts many coding idoms from Numpy, the biggest difference is that pandas is designed for working with tabular or heterogeneous data. Numpy, by contrast, is best suited for working with homogeneous numerical array data.

In [2]:
import pandas as pd
import numpy as np

## 5.1 Introduction to pandas Data structures
The two workhorse data structures are _Series_ & _DataFrame_

### Series
A series is a 1d array-like object containg a sequence of values and associated array of data label, called its **index**.

In [3]:
# the simples Series
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

The string representation of a Series displayed interactively shows the **index on the left** and **values on the right**. 

In [4]:
# array representation
obj.values

array([ 4,  7, -5,  3])

In [5]:
obj.index # like range(4)

RangeIndex(start=0, stop=4, step=1)

In [6]:
# create Series with an index identifying each data points with a label
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [7]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [8]:
# compared to numpy arrays, use labels in the index when selecting single or set of values
obj2['a']

-5

In [9]:
obj2['d'] = 6
obj2[['c', 'a', 'd']]  # ['c', 'a', 'd'] is interpreted as a list of indices even though their strings

c    3
a   -5
d    6
dtype: int64

In [10]:
# use numpy function or operation will preserve the index-value link
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [11]:
obj * 2

0     8
1    14
2   -10
3     6
dtype: int64

In [12]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [13]:
# another way to think about a Series is as a fixed-length, ordered dict
# as it is a mapping of index values to data values

In [14]:
'b' in obj2

True

In [15]:
'e' in obj2

False

In [16]:
# creating a Series from a Python dict
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)
obj3  # same index order as dict

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [17]:
# to overwrite order pass dict keys in the desired order
states = ['California', 'Ohio', 'Oregon', 'Texas']  # no Utah
obj4 = pd.Series(sdata, index=states)
obj4  # Cali has no value so NaN (not a number) is passed. Utah was not passed so it's excluded

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [18]:
# to detect missing data aka NaN values
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [19]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [20]:
# index labels automatically align in arithmetic operations
obj3 + obj4  # similiar to a join operation

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

Both the Series object itself and its indes have a name attribute, which integrates with other key areas of pandas functionality

In [21]:
obj4.name = 'population'
obj4.index.name = 'state'

In [22]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [23]:
# a Series's index can be altered in-plavr by assignment
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [24]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

### DataFrame
A DataFrame represents a rectangular table of data and contains an ordered collection of columns, each of which can be a different value type (numeric, string, boolean, etc.) The DataFrame has both a row and column index.

In [25]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
       'year': [2000, 2001, 2002, 2001, 2002, 2003], 
       'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
frame  # index is automatically assigned and columns are placed in sorted order

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002
5  3.2  Nevada  2003

In [26]:
# for large DataFrames, the head method selects only the first five rows
frame.head()

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [27]:
# specifying a sequence of colums will display the DataFrame columns in that order
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [28]:
# passing a column that isn't in the contained dict will result appear as a NaN column
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],  # debt not included in data
                     index=['one', 'two', 'three', 'four', 'five', 'six'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [29]:
frame2.columns  # debt is now a column in the DataFrame

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [30]:
# a column in a DataFrame can be retrieved as a Seried
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [31]:
frame2.state  # only works when the column name is a valid Python variable name

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [32]:
# rows can be retrieved by position or name using the special loc attribute
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [33]:
# columns can be modified entirely
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [34]:
frame2['debt'] = np.arange(6.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

when assigning lists or arrays to a column, the value's length must match the length of the DataFrame. Assigning a Series, its labels will be realigned exactly to the DataFrame's index, inserting missing values in any holes:

In [35]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [36]:
# assigning a column that doesn't exist will create a new column
# the del keyword will delete columns as with a dict
frame2['eastern'] = (frame2.state == 'Ohio')  # boolean column named eastern
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [37]:
del frame2['eastern']  # deletes eastern column
frame2.columns  # no more eastern

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [38]:
# another common form of data is a nested dict of dicts
pop = {'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame3 = pd.DataFrame(pop)
frame3  # a nested dict passed to DataFrame will interpret the outer dict keys as the columns
        # and the inner keys as the rows indices

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [39]:
# swap rows (index) and columns with tranpose (same as numpy)
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [40]:
# if index is explicitly defined it will be row labels
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [41]:
# dicts of Series are treached in much the same way
pdata = {'Ohio': frame3['Ohio'][:-1], 'Nevada': frame3['Nevada'][:2]}
pd.DataFrame(pdata)

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7

In [42]:
# if a DataFrame's index and columns have name attributes set, they will be displayed
frame3.index.name = '(year)'; frame3.columns.name = '(state)'
frame3

(state)  Nevada  Ohio
(year)               
2000        NaN   1.5
2001        2.4   1.7
2002        2.9   3.6

In [43]:
frame3.values  # like a Series it returns the data in the DataFrame as a 2d array

array([[ nan,  1.5],
       [ 2.4,  1.7],
       [ 2.9,  3.6]])

In [44]:
frame2.values  # different dtypes

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

### Index Objects
pandas's Index objects are responsible for holding the axis labels and other metadata (like the axis name or names). Any array or other sequence of labels you use when constructing a Series or DataFrame is internally converted to an Index

In [45]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [46]:
index[1:]

Index(['b', 'c'], dtype='object')

In [47]:
# index objects are immutable and can't be modified by the user
# index[1] = 'd'  # typeError

In [48]:
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [49]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)  # same result w/out providing index values
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [50]:
obj2.index is labels

True

In [51]:
# in addition to being array-like, an Index also behaves like a fixed-size set
frame3

(state)  Nevada  Ohio
(year)               
2000        NaN   1.5
2001        2.4   1.7
2002        2.9   3.6

In [52]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='(state)')

In [53]:
'Ohio' in frame3.columns

True

In [54]:
2003 in frame.index

False

In [55]:
# unlike Python sets, a pandas Index can contain duplicate labels
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])
dup_labels  # selections w/ duplicate labels will select all occurrences of that label

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

## 5.2 Essential Functionality
Fundamental mechanics of interacting with the data contained in a Series or DataFrame

### Reindexing
An important method on pandas objects is reindex, which means to create a new object with the data _conformed_ to a new index.

In [56]:
# E.g.
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [57]:
# Calling reindex on this Series rearranges the data according to the new index
# introducing NaN values if any index values were not already present
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])  # 'e' new index (not found in obj)
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

For ordered data like time series, it might be desirable to do some interpolation or filling of values when reindexing. The method option allows us to do this.

In [58]:
# method ffill (forward-fills the values) 
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [59]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [60]:
# reindex can alter either the (row) index, columns, or both
# when passed only a sequence, it reindexes the rows
frame = pd.DataFrame(np.arange(9).reshape((3, 3)), index=['a', 'c', 'd'],
                    columns=['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [61]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])  # 'b' is added so new row with NaN
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [62]:
# columns can be reindexed too wtih the columns keyword
states = ['Texas', 'Utah', 'California']
frame2.reindex(columns=states)

Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

In [63]:
# reindex can be done more succinctly by label-indexing with loc
frame.loc[['a', 'b', 'c', 'd'], states]  # label-indexing with loc has been deprecated

/Users/aaron/.pyenv/versions/3.5.4/envs/env3.5/lib/python3.5/site-packages/ipykernel_launcher.py:2: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  


Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

### Dropping Entries from an Axis
Dropping one or more entries from an axis is easy if you already have an index array or list without those entries. The drop method will return a new object with the indicated value or values deleted from an axis

In [64]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [65]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [66]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [67]:
# with DataFrame, index values can be deleted from either axis
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                   index=['Ohio', 'Colorado', 'Utah', 'New York'],
                   columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [68]:
# Calling drop with a sequence of labels will drop valies from the row labels (axis 0)
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [69]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [70]:
data.drop(['two', 'four'], axis=1)

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [71]:
# many functions, like drop, which modify the size or shape of a Series or DataFrame, can
# manipulate an object in-place without returning a new object
obj.drop('c', inplace=True)
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

### Indexing, Selection, and Filtering
Series indexing (obj[...]) works analogously to numpy array indexing, except you can use the Series's inddex values instead of only integers.

In [72]:
# E.g.
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [73]:
obj['b']

1.0

In [74]:
obj[1]

1.0

In [75]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [76]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [77]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [78]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [79]:
# slicing with labels behaves differently than normal Python slicing in that the ending
# point is inclusive
obj['b': 'c']

b    1.0
c    2.0
dtype: float64

In [80]:
# setting using these methods modifies the corresponding section of the Series
obj['b': 'c'] =5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [81]:
# Indexing into a DataFrame is for retrieving one or more columns 
# either with a single value or sequence
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                   index=['Ohio','Colorado', 'Utah', 'New York'],
                   columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [82]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [83]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [84]:
# indexing like this has a few special cases
data[:2]  # slicing data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [85]:
data[data['three'] > 5]  # slicing with boolean array

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [86]:
# The row selection syntax data[:2] is provided as a convenience. 
# Passing a single element or a list to the [] operator selects columns.

In [87]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [88]:
data[data < 5] = 0
data  # like 2d numpy arrays

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

### Selection with loc and iloc
loc and iloc enable you to select a subset of indices (rows) and columns from a DataFrame with numpy-like notation using either axis labels (loc) or integers (iloc)

In [89]:
# E.g. select a single row and multiple colums by label
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int64

In [90]:
data.iloc[2, [3, 0, 1]]  # similar to above but with integers

four    11
one      8
two      9
Name: Utah, dtype: int64

In [91]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [92]:
# both iloc and loc functions work with slices in addition to single labels or lists of labels
data.loc[: 'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [93]:
data.iloc[:, :3][data.three > 5]
# select all indices and first columns, then select those whose column three value is > 5

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

ix indexing operator still exists, but not recommended for use. (I don't like it either) :P

### Integer Indexes

In [94]:
ser = pd.Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [96]:
# does not work; trouble inferring between label-based or position based indexing
# ser[-1]

In [99]:
# no ambiguity with non-integer index
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])
ser2[-1]

2.0

In [100]:
# axis index containing integers will always be label-oriented
ser[:1]

0    0.0
dtype: float64

In [108]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

### Arithmetic and Data Alignment
An important pandas feature for some applications is the behavior of arithmetic between objects with different indexes. When adding together objects, if any index pairs are not the same, the respective index in the result will be the union of the index pairs.

In [109]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

In [110]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [111]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [113]:
s1 + s2  # internal data alignment introduces NaN in the labels locations
         # that don't overlap
         # this is also the case in DataFrames (both on rows and columns)

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

### Arithmetic Methods with fill values

In [118]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)), columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)), columns=list('abcde'))
df2.loc[1, 'b'] = np.nan

In [120]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [121]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [122]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [123]:
# to fill in NaN values
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [126]:
# can also fill when reindexing a Series or DataFrame
df1.reindex(columns=df2.columns, fill_value=0)  # only fills missing e column

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

### Operations between DataFrame and Series
Arithmetic between DataFrame and Series is also defined

In [127]:
# Numpy E.g.
arr = np.arange(12.).reshape((3, 4))
arr

array([[  0.,   1.,   2.,   3.],
       [  4.,   5.,   6.,   7.],
       [  8.,   9.,  10.,  11.]])

In [128]:
arr[0]

array([ 0.,  1.,  2.,  3.])

In [129]:
arr - arr[0]

array([[ 0.,  0.,  0.,  0.],
       [ 4.,  4.,  4.,  4.],
       [ 8.,  8.,  8.,  8.]])

In [130]:
# pandas E.g.
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                    columns=list('bde'),
                    index=['Utah', 'Ohio', 'Texas', 'Oregon'])
series = frame.iloc[0]
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [131]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [133]:
# by default arithmetic between Series and DataFrames matches the index
# of the Series on the DataFrame's columns, broadcasting down the rows
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [134]:
# is an index is not found in the Series's index or DataFrame's columns
# the objects will be reindex to form the union with corresponding NaN
series2 = pd.Series(range(3), index=['b', 'e', 'f'])
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [136]:
# broadcasting over the columns instead required use of arithmetic methods
series3 = frame['d']
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [137]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [144]:
# (frame - sub3) would be incorrect, we want subtraction over columns
frame.sub(series3, axis='index')  # axis = 0 also works

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

### Function Application and Mapping
Numpy ufuncs (elements-wise array methods) also work with pandas object

In [146]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
                    index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah   -0.306785 -1.964613 -0.592351
Ohio   -0.453620  0.821016  0.515391
Texas   0.391384  1.279249  1.429593
Oregon  1.358158 -1.054536 -0.282005

In [147]:
np.abs(frame)

b         d         e
Utah    0.306785  1.964613  0.592351
Ohio    0.453620  0.821016  0.515391
Texas   0.391384  1.279249  1.429593
Oregon  1.358158  1.054536  0.282005

In [148]:
# another frequent operation is applying a function on one-dimensional
# arrays to each column or row.
# DataFrame's apply metho does this
f = lambda x: x.max() - x.min()
frame.apply(f)  # takes diffence along columns of DataFrame returns Series

b    1.811778
d    3.243863
e    2.021944
dtype: float64

In [149]:
# to take difference along row pass axis='columns'
frame.apply(f, axis='columns')

Utah      1.657828
Ohio      1.274636
Texas     1.038209
Oregon    2.412694
dtype: float64

In [150]:
# returning more than scalar values with apply method
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])
frame.apply(f)

b         d         e
min -0.453620 -1.964613 -0.592351
max  1.358158  1.279249  1.429593

In [157]:
# apply a format string for each floating-point value in frame
formatt = lambda x: '%.2f' % x
frame.applymap(formatt)

b      d      e
Utah    -0.31  -1.96  -0.59
Ohio    -0.45   0.82   0.52
Texas    0.39   1.28   1.43
Oregon   1.36  -1.05  -0.28

In [158]:
# reason for the name applymap is that Series has a map method
# for applyin an element-wise function E.g.
frame['e'].map(formatt)=

Utah      -0.59
Ohio       0.52
Texas      1.43
Oregon    -0.28
Name: e, dtype: object

### Sorting and Ranking
To short alphabetically by row or column index, use sort_index method, which returns a new, sorted object

In [160]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [ ]:
# with a DataFrame you can sort by index on either axis
# E.g. DataFrame.sort_index(axis=1) sorts along columns

In [167]:
# to sort Series by its values, use sort_values method
# data sorted in ascending by default, for descending order pass False
obj = pd.Series([4, 7, -3, 2])
obj.sort_values(ascending=False)

1    7
0    4
3    2
2   -3
dtype: int64

In [170]:
# missing values sorted to the end of Series by default
obj = pd.Series([4, np.nan, 7, np.nan, -3, np.nan])
obj.sort_values()

4   -3.0
0    4.0
2    7.0
1    NaN
3    NaN
5    NaN
dtype: float64

In [173]:
# when sorting a DataFrame, the data in one or more columns can be used
# as the sort keys. To do so pass column(s) to the by option in sort_values
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})
frame

a  b
0  0  4
1  1  7
2  0 -3
3  1  2

In [175]:
frame.sort_values(by='b')  # sorting by column 'b'

a  b
2  0 -3
3  1  2
0  0  4
1  1  7

In [178]:
frame.sort_values(by=['a', 'b'])  # sorting by columns ['a', 'b']

a  b
2  0 -3
0  0  4
3  1  2
1  1  7

In [179]:
"""REVIEW: Rank method not clear"""
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

### Axis Indexes with Duplicate Labels


In [181]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [182]:
# index’s is_unique property tells whether its labels are unique or not
obj.index.is_unique

False

## 5.3 Summarizing and Computing Descriptive Statistics
pandas handles missing values (NaN) in common mathematical and statistical methods

In [194]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75, -1.3]],
                  index=['a', 'b', 'c', 'd'],
                  columns=['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [195]:
# sum method returns a Series containing columns sums
df.sum()  # ignores NA

one    9.25
two   -5.80
dtype: float64

In [196]:
df.sum(axis='columns')  # sums across columns

a    1.40
b    2.60
c     NaN
d   -0.55
dtype: float64

In [197]:
# NA values are ignore unless the entire slice (row or  column) is NA
# this can be disabled
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [198]:
# methods, like idxmin & idxmax, return indirect statstistics like the
# index value where min or max are attained
df.idxmax()

one    b
two    d
dtype: object

In [199]:
# other methods are accumulations
df.cumsum()  # cumsum across rows

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [200]:
# some methods are neither reduction or accumulation
df.describe()  # produces multiple summary statistics in one shot

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [201]:
# for non-numeric data, describe produces alternative summary statistics
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

### Correlation and Covariance
Some summary statistics, like correlation and covariance, are computed from pairs of arguments.

Consider some DataFrame of stock prices and volumes obtained from Yahoo! Finance using the add-on pandas-datareader package.

In [208]:
#import pandas_datareader.data as web
#all_data = {ticker: web.get_data_yahoo(ticker) 
#            for ticker in ['APPL', 'IBM', 'MSFT', 'GOOG']}
#price = pd.DataFrame({ticker: data['Adj Close']
#                     for ticker, data in all_data.items()})
#volume = pd.DataFrame({ticker: data['Volume']
#                      for ticker, data in all_data.items()})
"""Not working will try to solve later"""

'Not working will try to solve later'